import 'package:conecta_app/models/info_livros.dart';

List<Livros> livrosList = [
  const Livros(
    id: '1', 
    title: 'Competências e Habilidades para uma Educação 3.0',
    resumo: 'Resumo',
    descricao: 'O predomínio e a onipresença das linguagens midiáticas no século 21 exigem novas habilidades e competências para o exercício da cidadania. Incorporar tais competências no desenvolvimento do profissionalismo docente é necessário, urgente e um projeto a ser construído ao longo da carreira. Os professores respondem pela formação direta da cidadania de seus estudantes que precisam exercitar a proatividade no campo social por meio de mídias digitais. É disso que as autoras se ocupam no livro.',
    autor: 'Marie Jane Soares Carvalho, \nViviane Toraci Alonso de Andrade',
    imageAsset: 'assets/editora/capaLivros/CompetênciaseHabilidades.png', 
    verMais: 'Ver Mais',
    pdfAsset: 'assets/editora/pdfLivros/livro_competenciaseHabilidades.pdf',
  ),
  const Livros(
    id: '2', 
    title: 'Ciranda Pernambucana - Antologia Poética Infanto Juvenil',
    resumo: 'Resumo',
    descricao: 'O livro reúne poemas de 15 poetas pernambucanos ou radicados em Pernambuco. Aqui encontra-se uma seleção de poemas que podem atrair jovens – e também adultos – ao universo da leitura, pequenos textos que refletem sobre o tempo mágico da infância e dos primeiros anos de adolescência.',
    autor: 'Liliane Maria Jamir e Silva',
    imageAsset: 'assets/editora/capaLivros/CirandaPernambucana.png', 
    verMais: 'Ver Mais',
    pdfAsset: 'assets/editora/pdfLivros/livro_cirandaPernambucana.pdf',
  ),
  const Livros(
    id: '3', 
    title: 'Energia, organizações e sociedade: um debate necessário',
    resumo: 'Resumo',
    descricao: 'Energia, organizações e sociedade: um debate necessário é uma obra de caráter interdisciplinar que propõe o diálogo acerca do investimento em usinas hidroelétricas, atentando para o conflito de interesses entre empresários e a população local',
    autor: 'Luiz Alex Silva Saraiva, \nAdriana Vinholi Rampazo',
    imageAsset: 'assets/editora/capaLivros/EnergiaOrganizaçõesESociedade.png', 
    verMais: 'Ver Mais',
    pdfAsset: 'assets/editora/pdfLivros/livro_energia.pdf',
  ),
  const Livros(
    id: '4', 
    title: 'Políticas e gestão da Educação: Pesquisa Educacional em Pernambuco',
    resumo: 'Resumo', 
    descricao: 'Este livro faz parte da trilogia com textos do VI Encontro de Pesquisa Educacional de Pernambuco. O tema das políticas educacionais permeia todos os textos em suas diversas nuanças. A obra em suma aponta para questões relativas ao Plano Nacional de Educação, como um referencial para construção das políticas educacionais. Algumas destas políticas são analisadas nos artigos reunidos nesta publicação, que tem como objetivo tornar pública a produção acadêmica no campo da pesquisa educacional.',
    autor: 'Cibele Maria Lima Rodrigues, \nPatrícia Maria Uchôa Simões, \nLuciana Rosa Marques, \nEdnaldo Ferreira Torres',
    imageAsset: 'assets/editora/capaLivros/PolíticasEGestão.png', 
    verMais: 'Ver Mais',
    pdfAsset: 'assets/editora/pdfLivros/livro_PolíticasEGestão.pdf',
  ),
  const Livros(
    id: '5', 
    title: 'Práticas pedagógicas e formação de professores em contextos diferenciados',
    resumo: 'Resumo', 
    descricao:'A obra Práticas pedagógicas e formação de professores em contextos diferenciados, integrante da trilogia do VI Encontro de Pesquisa Educacional de Pernambuco (EPEPE) enaltece a perseverança de profissionais que promovem profundas mudanças nos diversos contextos educacionais do Estado. O título aborda as contribuições para o processo de alfabetização a partir dos estudos de “esquemas” por meio de ação de professores em contextos de diversidades da aprendizagem.',
    autor: 'Cibele Maria Lima Rodrigues, \nPatrícia Maria Uchôa Simões, \nLuciana Rosa Marques, \nEdnaldo Ferreira Torres',
    imageAsset: 'assets/editora/capaLivros/PráticasPedagógicas.png', 
    verMais: 'Ver Mais',
    pdfAsset: 'assets/editora/pdfLivros/livro_PráticasPedagógicas.pdf',
  ),
];