import 'package:conecta_app/models/info_livros.dart';

const livrosList = [
    Livros(
    id: '1', 
    title: 'Competências e Habilidades para uma Educação 3.0',
    resumo: 'Resumo',
    descricao: 'O predomínio e a onipresença das linguagens midiáticas no século 21 exigem novas habilidades e competências para o exercício da cidadania. Incorporar tais competências no desenvolvimento do profissionalismo docente é necessário, urgente e um projeto a ser construído ao longo da carreira. Os professores respondem pela formação direta da cidadania de seus estudantes que precisam exercitar a proatividade no campo social por meio de mídias digitais. É disso que as autoras se ocupam no livro.',
    autor: 'Marie Jane Soares Carvalho, \nViviane Toraci Alonso de Andrade',
    imageAsset: 'assets/editora/capaLivros/CompetênciaseHabilidades.png', 
    verMais: 'Ver Mais',
    url: 'https://www.gov.br/fundaj/pt-br/composicao/dimeca-1/editora-teste/livros-pdf/competencias-e-habilidades-para-uma-educacao-3-0.pdf',
  ),
    Livros(
    id: '2', 
    title: 'Ciranda Pernambucana - Antologia Poética Infanto Juvenil',
    resumo: 'Resumo',
    descricao: 'O livro reúne poemas de 15 poetas pernambucanos ou radicados em Pernambuco. Aqui encontra-se uma seleção de poemas que podem atrair jovens – e também adultos – ao universo da leitura, pequenos textos que refletem sobre o tempo mágico da infância e dos primeiros anos de adolescência.',
    autor: 'Liliane Maria Jamir e Silva',
    imageAsset: 'assets/editora/capaLivros/CirandaPernambucana.png', 
    verMais: 'Ver Mais',
    url: 'https://www.gov.br/fundaj/pt-br/composicao/dimeca-1/editora-teste/livros-pdf/ciranda-pernambucana.pdf',
  ),
    Livros(
    id: '3', 
    title: 'Cultura Viva do Nordeste – Perfis dos 90 vencedores do Prêmio Delmiro Gouveia de Economia Criativa',
    resumo: 'Resumo',
    descricao: 'Cultura viva do Nordeste é, na sua estrutura, uma longa reportagem. Cada retrato ou perfil compõe, na sua heterogeneidade, a unidade fundamental traduzida numa narrativa tão cheia de calor humano quanto os personagens que aborda. Sem perder a objetividade e a sobriedade, que são virtudes do jornalismo orgulhoso de dizer o próprio nome. O Prêmio Delmiro Gouveia de Economia Criativa que tem neste livro um importante registro de memória, com pitadas de história oral, é parte de uma realização mais ampla.',
    autor: 'Karla Veloso',
    imageAsset: 'assets/editora/capaLivros/CulturaVivaDoNordeste.png', 
    verMais: 'Ver Mais',
    url: 'https://www.gov.br/fundaj/pt-br/composicao/dimeca-1/editora-teste/livros-pdf/cultura-viva-do-nordeste.pdf',
  ),
  Livros(
    id: '4', 
    title: 'Gilberto Freyre & a Educação',
    resumo: 'Resumo', 
    descricao: 'O que se apresenta neste livro é fruto de uma série de reflexões que o professor e sociólogo Amurabi Oliveira vem realizando sobre o pensamento de Gilberto Freyre. A partir dessas reflexões, tem sido enfatizada a relevância do sociólogo pernambucano como um pensador das ciências sociais que possui uma contribuição valiosa para a educação, destacando assim seu lugar como pensador educacional. A relevância de revisitar o pensamento de Gilberto Freyre a partir desse ângulo deve-se ao fato de que continua atual sua proposta pedagógica, a partir de uma forte articulação entre o mundo social e os conhecimentos teóricos.',
    autor: 'Amurabi Oliveira ',
    imageAsset: 'assets/editora/capaLivros/GilbertoFreyre&aEducação.png', 
    verMais: 'Ver Mais',
    url: 'https://www.gov.br/fundaj/pt-br/composicao/dimeca-1/editora-teste/livros-pdf/gilberto-freyre-a-educacao-digital.pdf',
  ),
  Livros(
    id: '5', 
    title: 'A Sudene e seu Inventor',
    resumo: 'Resumo', 
    descricao:'A obra Práticas pedagógicas e formação de professores em contextos diferenciados, integrante da trilogia do VI Encontro de Pesquisa Educacional de Pernambuco (EPEPE) enaltece a perseverança de profissionais que promovem profundas mudanças nos diversos contextos educacionais do Estado. O título aborda as contribuições para o processo de alfabetização a partir dos estudos de “esquemas” por meio de ação de professores em contextos de diversidades da aprendizagem.',
    autor: 'Clemente Rosas',
    imageAsset: 'assets/editora/capaLivros/ASudeneeseuInventor.png', 
    verMais: 'Ver Mais',
    url: 'https://www.gov.br/fundaj/pt-br/composicao/dimeca-1/editora-teste/livros-pdf/a-sudene-e-seu-inventor.pdf',
  ),
];